"""

Revision ID: 3083c60216f1
Revises: eeca0b537919
Create Date: 2024-06-06 11:46:20.437484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_kingbase


# revision identifiers, used by Alembic.
revision: str = '3083c60216f1'
down_revision: Union[str, None] = 'eeca0b537919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_teacher_transaction', 'transaction_type',
               existing_type=sa.VARCHAR(length=255),
               comment='变动类型',
               existing_comment='异动类型',
               existing_nullable=True)
    op.alter_column('lfun_teacher_transaction', 'transaction_time',
               existing_type=sqlalchemy_kingbase.types.TIMESTAMP(),
               comment='操作时间',
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_column('lfun_teacher_transaction', 'transaction_reason')
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 153")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 2")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 150")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 156")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 5")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 149")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 152")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.307565', updated_at='2024-06-06 11:46:20.307565' WHERE lfun_course.id = 1")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 158")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 155")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 151")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 154")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 11:46:20.355536', updated_at='2024-06-06 11:46:20.355536' WHERE lfun_course.id = 157")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lfun_teacher_transaction', sa.Column('transaction_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='异动原因'))
    op.alter_column('lfun_teacher_transaction', 'transaction_time',
               existing_type=sqlalchemy_kingbase.types.TIMESTAMP(),
               comment='创建时间',
               existing_comment='操作时间',
               existing_nullable=False)
    op.alter_column('lfun_teacher_transaction', 'transaction_type',
               existing_type=sa.VARCHAR(length=255),
               comment='异动类型',
               existing_comment='变动类型',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 159')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 160')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 161')
    # ### end Alembic commands ###
