"""

Revision ID: 502f563cc509
Revises: 906a8a3da7d9
Create Date: 2024-06-06 14:00:16.142065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502f563cc509'
down_revision: Union[str, None] = '906a8a3da7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_teacher_transaction', 'transaction_id',
               existing_type=sa.INTEGER(),
               comment='变动主键id',
               existing_comment='教师变动ID主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lfun_teacher_transaction', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='教师ID')
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 153")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 2")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 150")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 156")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 5")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 149")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 152")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.948090', updated_at='2024-06-06 14:00:15.948090' WHERE lfun_course.id = 1")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 158")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 155")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 151")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 154")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:00:15.996876', updated_at='2024-06-06 14:00:15.996876' WHERE lfun_course.id = 157")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_teacher_transaction', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='教师ID')
    op.alter_column('lfun_teacher_transaction', 'transaction_id',
               existing_type=sa.INTEGER(),
               comment='教师变动ID主键',
               existing_comment='变动主键id',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 159')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 160')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 161')
    # ### end Alembic commands ###
