"""

Revision ID: 5c0b4c59bd9c
Revises: 242a7664121d
Create Date: 2024-06-06 15:27:59.027673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0b4c59bd9c'
down_revision: Union[str, None] = '242a7664121d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'school_type',
               existing_type=sa.VARCHAR(length=64),
               comment='教育阶段/学校类别 例如 小学 初中 多个逗号隔开',
               existing_comment='教育阶段/学校类别 例如   多个逗号隔开',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'school_type',
               existing_type=sa.VARCHAR(length=64),
               comment='教育阶段/学校类别 例如   多个逗号隔开',
               existing_comment='教育阶段/学校类别 例如 小学 初中 多个逗号隔开',
               existing_nullable=True)
    # ### end Alembic commands ###
