"""

Revision ID: 725e9f026382
Revises: 056b1628562d
Create Date: 2024-06-11 11:01:55.237430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725e9f026382'
down_revision: Union[str, None] = '056b1628562d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lfun_course_school_nature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('course_no', sa.String(length=24), nullable=True, comment='学科编码'),
    sa.Column('school_nature', sa.String(length=64), nullable=True, comment='学校性质 2级或者3级'),
    sa.Column('created_uid', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('updated_uid', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='删除态'),
    sa.PrimaryKeyConstraint('id'),
    comment='课程和学校关系表模型'
    )
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_table('lfun_course_school_nature')
    # ### end Alembic commands ###
