"""

Revision ID: 7e234e8acd3e
Revises: dc36ff7d70ac
Create Date: 2024-06-05 10:04:14.575992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e234e8acd3e'
down_revision: Union[str, None] = 'dc36ff7d70ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_grade', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.add_column('lfun_teachers', sa.Column('teacher_approval_status', sa.String(length=64), nullable=True, comment='审批状态'))
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 153")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 2")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 150")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 156")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 5")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 149")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 152")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.450547', updated_at='2024-06-05 10:04:14.450547' WHERE lfun_course.id = 1")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 158")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 155")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 151")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 154")
    op.execute("UPDATE lfun_course SET created_at='2024-06-05 10:04:14.499354', updated_at='2024-06-05 10:04:14.499354' WHERE lfun_course.id = 157")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lfun_teachers', 'teacher_approval_status')
    op.alter_column('lfun_grade', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 159')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 160')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 161')
    # ### end Alembic commands ###
