"""

Revision ID: 8f36c88ec531
Revises: d586112bc211
Create Date: 2024-06-06 09:54:36.180156

"""
from typing import Sequence, Union
import sqlalchemy_kingbase
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f36c88ec531'
down_revision: Union[str, None] = 'd586112bc211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_storage', 'state',
               existing_type=sqlalchemy_kingbase.named_types.ENUM('wait', 'uploading', 'uploaded', 'failed', name='filestate'),
               type_=sa.String(),
               existing_comment='状态',
               existing_nullable=False)
    op.add_column('lfun_classes', sa.Column('session_name', sa.String(length=64), nullable=True, comment='届别名称'))
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_grade', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='学校ID')
    op.alter_column('lfun_grade', 'city',
               existing_type=sa.VARCHAR(length=64),
               comment='城市 编码',
               existing_comment='城市',
               existing_nullable=True)
    op.alter_column('lfun_grade', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='区 编码',
               existing_nullable=True)
    op.add_column('lfun_task_progress', sa.Column('progress_id', sa.Integer(), autoincrement=True, nullable=False, comment='进度ID'))
    op.add_column('lfun_task_progress', sa.Column('progress_desc', sa.String(), nullable=True, comment='任务进度描述'))
    op.alter_column('lfun_task_progress', 'task_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='任务ID',
               existing_nullable=False)
    op.create_index(op.f('ix_lfun_task_progress_task_id'), 'lfun_task_progress', ['task_id'], unique=False)
    op.drop_column('lfun_task_progress', 'process_desc')
    op.add_column('lfun_task_results', sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False, comment='结果ID'))
    op.alter_column('lfun_task_results', 'task_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='任务ID',
               existing_nullable=False)
    op.create_index(op.f('ix_lfun_task_results_task_id'), 'lfun_task_results', ['task_id'], unique=False)
    op.alter_column('lfun_tasks', 'task_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='任务ID',
               existing_nullable=False)
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 153")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 2")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 150")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 156")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 5")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 149")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 152")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:35.982462', updated_at='2024-06-06 09:54:35.982462' WHERE lfun_course.id = 1")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 158")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 155")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 151")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 154")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 09:54:36.076646', updated_at='2024-06-06 09:54:36.076646' WHERE lfun_course.id = 157")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_tasks', 'task_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='任务ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_lfun_task_results_task_id'), table_name='lfun_task_results')
    op.alter_column('lfun_task_results', 'task_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='任务ID',
               existing_nullable=False)
    op.drop_column('lfun_task_results', 'result_id')
    op.add_column('lfun_task_progress', sa.Column('process_desc', sa.VARCHAR(), autoincrement=False, nullable=False, comment='任务进度描述'))
    op.drop_index(op.f('ix_lfun_task_progress_task_id'), table_name='lfun_task_progress')
    op.alter_column('lfun_task_progress', 'task_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='任务ID',
               existing_nullable=False)
    op.drop_column('lfun_task_progress', 'progress_desc')
    op.drop_column('lfun_task_progress', 'progress_id')
    op.alter_column('lfun_grade', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='区 编码',
               existing_nullable=True)
    op.alter_column('lfun_grade', 'city',
               existing_type=sa.VARCHAR(length=64),
               comment='城市',
               existing_comment='城市 编码',
               existing_nullable=True)
    op.alter_column('lfun_grade', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='学校ID')
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('lfun_classes', 'session_name')
    op.alter_column('file_storage', 'state',
               existing_type=sa.String(),
               type_=sqlalchemy_kingbase.named_types.ENUM('wait', 'uploading', 'uploaded', 'failed', name='filestate'),
               existing_comment='状态',
               existing_nullable=False)
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 159')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 160')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 161')
    # ### end Alembic commands ###
