"""

Revision ID: a76e505be057
Revises: 725e9f026382
Create Date: 2024-06-11 13:32:23.588315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_kingbase


# revision identifiers, used by Alembic.
revision: str = 'a76e505be057'
down_revision: Union[str, None] = '725e9f026382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_organization_members', 'member_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='姓名')
    op.alter_column('lfun_organization_members', 'member_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='成员类型/岗位 例如老师 领导 职工等')
    op.alter_column('lfun_organization_members', 'birthday',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='生日')
    op.alter_column('lfun_organization_members', 'gender',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='性别')
    op.alter_column('lfun_organization_members', 'mobile',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='手机')
    op.alter_column('lfun_organization_members', 'card_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='证件类型')
    op.alter_column('lfun_organization_members', 'card_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='证件号码')
    op.alter_column('lfun_organization_members', 'created_at',
               existing_type=sqlalchemy_kingbase.types.TIMESTAMP(),
               nullable=True,
               existing_comment='创建时间')
    op.alter_column('lfun_organization_members', 'updated_at',
               existing_type=sqlalchemy_kingbase.types.TIMESTAMP(),
               nullable=True,
               existing_comment='更新时间')
    op.alter_column('lfun_organization_members', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='删除态')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_organization_members', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='删除态')
    op.alter_column('lfun_organization_members', 'updated_at',
               existing_type=sqlalchemy_kingbase.types.TIMESTAMP(),
               nullable=False,
               existing_comment='更新时间')
    op.alter_column('lfun_organization_members', 'created_at',
               existing_type=sqlalchemy_kingbase.types.TIMESTAMP(),
               nullable=False,
               existing_comment='创建时间')
    op.alter_column('lfun_organization_members', 'card_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='证件号码')
    op.alter_column('lfun_organization_members', 'card_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='证件类型')
    op.alter_column('lfun_organization_members', 'mobile',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='手机')
    op.alter_column('lfun_organization_members', 'gender',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='性别')
    op.alter_column('lfun_organization_members', 'birthday',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='生日')
    op.alter_column('lfun_organization_members', 'member_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='成员类型/岗位 例如老师 领导 职工等')
    op.alter_column('lfun_organization_members', 'member_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='姓名')
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
