"""

Revision ID: a94ee11d03c2
Revises: 897bd40b2623
Create Date: 2024-06-06 14:40:25.126225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94ee11d03c2'
down_revision: Union[str, None] = '897bd40b2623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lfun_teacher_transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False, comment='变动主键id'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师ID'),
    sa.Column('transaction_type', sa.String(length=255), nullable=True, comment='变动类型'),
    sa.Column('transaction_remark', sa.String(length=255), nullable=False, comment='备注'),
    sa.Column('original_position', sa.String(length=64), nullable=False, comment='原任职岗位'),
    sa.Column('current_position', sa.String(length=64), nullable=False, comment='现任职岗位'),
    sa.Column('position_date', sa.Date(), nullable=False, comment='任职日期'),
    sa.Column('transaction_time', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.Column('operator_name', sa.String(length=255), nullable=False, comment='操作人'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('approval_status', sa.String(length=255), nullable=False, comment='审批状态'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='删除态'),
    sa.PrimaryKeyConstraint('transaction_id'),
    comment='教师变动修改表'
    )
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 153")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 2")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 150")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 156")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 5")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 149")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 152")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.916081', updated_at='2024-06-06 14:40:24.916081' WHERE lfun_course.id = 1")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 158")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 155")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 151")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 154")
    op.execute("UPDATE lfun_course SET created_at='2024-06-06 14:40:24.967944', updated_at='2024-06-06 14:40:24.967944' WHERE lfun_course.id = 157")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_table('lfun_teacher_transaction')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 159')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 160')
    op.execute('DELETE FROM lfun_course WHERE lfun_course.id = 161')
    # ### end Alembic commands ###
