"""

Revision ID: c4418916f6e7
Revises: a76e505be057
Create Date: 2024-06-11 15:10:47.200251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_kingbase
import sqlalchemy_kingbase.named_types
from sqlalchemy.types import TIMESTAMP

# revision identifiers, used by Alembic.
revision: str = 'c4418916f6e7'
down_revision: Union[str, None] = 'a76e505be057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.add_column('lfun_task_results', sa.Column('result_bucket', sa.String(), nullable=False, comment='结果桶'))
    op.add_column('lfun_task_results', sa.Column('result_file_id', sa.Integer(), nullable=False, comment='结果文件ID'))
    op.add_column('lfun_teacher_transaction', sa.Column('process_instance_id', sa.Integer(), nullable=False, comment='流程ID'))
    op.add_column('lfun_teachers', sa.Column('identity', sa.String(length=64), nullable=True, comment='身份'))
    op.add_column('lfun_teachers', sa.Column('mobile', sa.String(length=64), nullable=True, comment='手机号'))
    op.add_column('lfun_teachers_info', sa.Column('department', sa.String(length=255), nullable=True, comment='部门'))
    op.add_column('lfun_transfer_details', sa.Column('original_region', sa.String(length=64), nullable=True, comment='原管辖区域'))
    op.add_column('lfun_transfer_details', sa.Column('current_region', sa.String(length=64), nullable=True, comment='现管辖区域'))
    op.add_column('lfun_transfer_details', sa.Column('process_instance_id', sa.Integer(), nullable=False, comment='流程ID'))
    op.alter_column('lfun_transfer_details', 'original_unit',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='原单位')
    op.alter_column('lfun_transfer_details', 'original_position',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='原岗位')
    op.alter_column('lfun_transfer_details', 'original_district',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='原行政属地')
    op.alter_column('lfun_transfer_details', 'transfer_in_date',
               existing_type=sqlalchemy_kingbase.named_types.DOMAIN('date', TIMESTAMP()),
               nullable=True,
               existing_comment='调入日期')
    op.alter_column('lfun_transfer_details', 'current_unit',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='现单位')
    op.alter_column('lfun_transfer_details', 'current_position',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='现岗位')
    op.alter_column('lfun_transfer_details', 'current_district',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='现行政属地')
    op.alter_column('lfun_transfer_details', 'transfer_out_date',
               existing_type=sqlalchemy_kingbase.named_types.DOMAIN('date', TIMESTAMP()),
               nullable=True,
               existing_comment='调出日期')
    op.alter_column('lfun_transfer_details', 'transfer_reason',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='调动原因')
    op.alter_column('lfun_transfer_details', 'remark',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='备注')
    op.alter_column('lfun_transfer_details', 'operator_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='操作人')
    op.alter_column('lfun_transfer_details', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='教师ID')
    op.alter_column('lfun_transfer_details', 'operation_time',
               existing_type=sqlalchemy_kingbase.named_types.DOMAIN('date', TIMESTAMP()),
               type_=sa.DateTime(),
               existing_comment='操作时间',
               existing_nullable=False)
    op.add_column('lfun_work_flow__instance', sa.Column('applicant_name', sa.String(length=64), nullable=False, comment='申请人姓名'))
    op.add_column('lfun_work_flow__instance', sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师ID'))
    op.create_table_comment(
        'lfun_work_flow__instance',
        'work_flow_instance信息表',
        existing_comment='work_flow__instance信息表',
        schema=None
    )
    op.drop_column('lfun_work_flow__instance', 'applicant_id')
    op.add_column('lfun_work_flow_node_instance', sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师ID'))
    op.add_column('lfun_work_flow_node_instance', sa.Column('operator_name', sa.String(length=64), nullable=False, comment='操作人姓名'))
    op.drop_column('lfun_work_flow_node_instance', 'operator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lfun_work_flow_node_instance', sa.Column('operator_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='操作人id'))
    op.drop_column('lfun_work_flow_node_instance', 'operator_name')
    op.drop_column('lfun_work_flow_node_instance', 'teacher_id')
    op.add_column('lfun_work_flow__instance', sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='申请人id'))
    op.create_table_comment(
        'lfun_work_flow__instance',
        'work_flow__instance信息表',
        existing_comment='work_flow_instance信息表',
        schema=None
    )
    op.drop_column('lfun_work_flow__instance', 'teacher_id')
    op.drop_column('lfun_work_flow__instance', 'applicant_name')
    op.alter_column('lfun_transfer_details', 'operation_time',
               existing_type=sa.DateTime(),
               type_=sqlalchemy_kingbase.named_types.DOMAIN('date', TIMESTAMP()),
               existing_comment='操作时间',
               existing_nullable=False)
    op.alter_column('lfun_transfer_details', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='教师ID')
    op.alter_column('lfun_transfer_details', 'operator_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='操作人')
    op.alter_column('lfun_transfer_details', 'remark',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='备注')
    op.alter_column('lfun_transfer_details', 'transfer_reason',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='调动原因')
    op.alter_column('lfun_transfer_details', 'transfer_out_date',
               existing_type=sqlalchemy_kingbase.named_types.DOMAIN('date', TIMESTAMP()),
               nullable=False,
               existing_comment='调出日期')
    op.alter_column('lfun_transfer_details', 'current_district',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='现行政属地')
    op.alter_column('lfun_transfer_details', 'current_position',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='现岗位')
    op.alter_column('lfun_transfer_details', 'current_unit',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='现单位')
    op.alter_column('lfun_transfer_details', 'transfer_in_date',
               existing_type=sqlalchemy_kingbase.named_types.DOMAIN('date', TIMESTAMP()),
               nullable=False,
               existing_comment='调入日期')
    op.alter_column('lfun_transfer_details', 'original_district',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='原行政属地')
    op.alter_column('lfun_transfer_details', 'original_position',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='原岗位')
    op.alter_column('lfun_transfer_details', 'original_unit',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='原单位')
    op.drop_column('lfun_transfer_details', 'process_instance_id')
    op.drop_column('lfun_transfer_details', 'current_region')
    op.drop_column('lfun_transfer_details', 'original_region')
    op.drop_column('lfun_teachers_info', 'department')
    op.drop_column('lfun_teachers', 'mobile')
    op.drop_column('lfun_teachers', 'identity')
    op.drop_column('lfun_teacher_transaction', 'process_instance_id')
    op.drop_column('lfun_task_results', 'result_file_id')
    op.drop_column('lfun_task_results', 'result_bucket')
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
