"""

Revision ID: dc36ff7d70ac
Revises: 103eb8c09c43
Create Date: 2024-06-04 16:24:13.154479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc36ff7d70ac'
down_revision: Union[str, None] = '103eb8c09c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_grade', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_work_flow__instance', 'applicant_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_comment='申请人id',
               existing_nullable=False)
    op.alter_column('lfun_work_flow_node_instance', 'operator_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_comment='操作人id',
               existing_nullable=False)
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 153")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 2")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 150")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 156")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 5")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 149")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 152")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.050799', updated_at='2024-06-04 16:24:13.050799' WHERE lfun_course.id = 1")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 158")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 155")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 151")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 154")
    op.execute("UPDATE lfun_course SET district='', created_at='2024-06-04 16:24:13.097381', updated_at='2024-06-04 16:24:13.097381' WHERE lfun_course.id = 157")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_work_flow_node_instance', 'operator_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_comment='操作人id',
               existing_nullable=False)
    op.alter_column('lfun_work_flow__instance', 'applicant_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_comment='申请人id',
               existing_nullable=False)
    op.alter_column('lfun_grade', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
