"""

Revision ID: edf1bec8c72b
Revises: b9ff3cb3b188
Create Date: 2024-06-13 11:40:30.359850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf1bec8c72b'
down_revision: Union[str, None] = 'b9ff3cb3b188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_course_school_nature', 'school_nature',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=40),
               existing_comment='学校性质 2级或者3级',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course_school_nature', 'school_nature',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=64),
               existing_comment='学校性质 2级或者3级',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
