"""

Revision ID: f06fc6e22ef4
Revises: 2adb0662a084
Create Date: 2024-06-14 11:38:14.438108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06fc6e22ef4'
down_revision: Union[str, None] = '2adb0662a084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='',
               existing_nullable=True)
    op.add_column('lfun_major', sa.Column('city', sa.String(length=64), nullable=True, comment='城市'))
    op.add_column('lfun_major', sa.Column('district', sa.String(length=64), nullable=True))
    op.alter_column('lfun_major', 'major_id',
               existing_type=sa.VARCHAR(length=24),
               comment='专业code',
               existing_comment='专业ID',
               existing_nullable=True)
    op.alter_column('lfun_major', 'major_id_lv2',
               existing_type=sa.VARCHAR(length=24),
               comment='2级专业code',
               existing_comment='2级专业ID',
               existing_nullable=True)
    op.alter_column('lfun_major', 'major_id_lv3',
               existing_type=sa.VARCHAR(length=24),
               comment='3级专业code',
               existing_comment='3级专业ID',
               existing_nullable=True)
    op.alter_column('lfun_task_progress', 'progress_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_comment='进度ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lfun_task_results', 'result_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_comment='结果ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lfun_task_results', 'result_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_comment='结果ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lfun_task_progress', 'progress_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_comment='进度ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lfun_major', 'major_id_lv3',
               existing_type=sa.VARCHAR(length=24),
               comment='3级专业ID',
               existing_comment='3级专业code',
               existing_nullable=True)
    op.alter_column('lfun_major', 'major_id_lv2',
               existing_type=sa.VARCHAR(length=24),
               comment='2级专业ID',
               existing_comment='2级专业code',
               existing_nullable=True)
    op.alter_column('lfun_major', 'major_id',
               existing_type=sa.VARCHAR(length=24),
               comment='专业ID',
               existing_comment='专业code',
               existing_nullable=True)
    op.drop_column('lfun_major', 'district')
    op.drop_column('lfun_major', 'city')
    op.alter_column('lfun_education_year', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('lfun_course', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
